trigger:
- dotnet

pool:
 name: Hosted VS2017

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dotnet'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'OTA-PRD-573 (7db14119-8eab-48d0-9ba2-26d0bd9deab1)'
    appType: 'webApp'
    WebAppName: 'HighTableWebApp'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
