trigger:
- dotnet

pool:
 name: Hosted VS2017

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dotnet'
    publishLocation: 'Container'

